# Generated by Django 2.1.1 on 2018-09-11 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=255, verbose_name='Страна')),
                ('region', models.CharField(max_length=255, verbose_name='Область')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('street_name', models.CharField(max_length=255, verbose_name='Улица')),
                ('building_number', models.CharField(max_length=255, verbose_name='Номер дома')),
                ('building_letter', models.CharField(blank=True, default='', max_length=255, verbose_name='Буква дома')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='auth.Group', verbose_name='Группа')),
            ],
            options={
                'verbose_name_plural': 'Адреса',
                'verbose_name': 'Адрес',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование компании')),
                ('description', models.CharField(max_length=255, verbose_name='Деталировка компании')),
                ('client', models.BooleanField(default=True, verbose_name='Клиент')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='auth.Group', verbose_name='Группа')),
            ],
            options={
                'verbose_name_plural': 'Компании',
                'verbose_name': 'Компания',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=7)),
                ('date_from', models.DateField(verbose_name='Дата начала договора')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='Дата окончания договора')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='backend.Company', verbose_name='Заказчик')),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executors', to='backend.Company', verbose_name='Исполнитель')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='auth.Group', verbose_name='Группа')),
            ],
            options={
                'verbose_name_plural': 'Договора',
                'verbose_name': 'Договор',
            },
        ),
        migrations.CreateModel(
            name='LegacyEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=32, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=32, verbose_name='Отчествео')),
                ('document', models.CharField(max_length=255, verbose_name='На основании какого документа')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legacyentity', to='auth.Group', verbose_name='Группа')),
            ],
            options={
                'verbose_name_plural': 'Юридические лица',
                'verbose_name': 'Юридическое лицо',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveSmallIntegerField(blank=True, default=1, verbose_name='Количество услуг')),
                ('date_from', models.DateField(blank=True, null=True, verbose_name='Дата начала предоставления услуги')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='Дата окончания предоставления услуги')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Комментарий')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Цена услуги')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to='backend.Address', verbose_name='Адрес')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='backend.Contract', verbose_name='Договор')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service', to='auth.Group', verbose_name='Группа')),
            ],
            options={
                'verbose_name_plural': 'Услуги',
                'verbose_name': 'Услуга',
            },
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Цена услуги')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicetype', to='auth.Group', verbose_name='Группа')),
            ],
            options={
                'verbose_name_plural': 'Типы сервисных услуг',
                'verbose_name': 'Тип сервисной услуги',
            },
        ),
        migrations.CreateModel(
            name='StreetType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
                ('short_name', models.CharField(max_length=4)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='streettype', to='auth.Group', verbose_name='Группа')),
            ],
            options={
                'verbose_name_plural': 'Типы улиц',
                'verbose_name': 'Тип улицы',
            },
        ),
        migrations.AddField(
            model_name='service',
            name='type_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='services', to='backend.ServiceType', verbose_name='Тип услуги'),
        ),
        migrations.AddField(
            model_name='company',
            name='legacy_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='backend.LegacyEntity', verbose_name='Юридическое лицо'),
        ),
        migrations.AddField(
            model_name='address',
            name='street_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.StreetType', verbose_name='Тип улицы'),
        ),
    ]
