# Generated by Django 2.1.1 on 2018-09-04 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=255, verbose_name='Страна')),
                ('region', models.CharField(max_length=255, verbose_name='Область')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('street_name', models.CharField(max_length=255, verbose_name='Улица')),
                ('building_number', models.CharField(max_length=255, verbose_name='Номер дома')),
                ('building_letter', models.CharField(blank=True, default='', max_length=255, verbose_name='Буква дома')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=7)),
                ('date_from', models.DateField(verbose_name='Дата начала договора')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='Дата окончания договора')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договора',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('client', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveSmallIntegerField(blank=True, default=1, verbose_name='Количество услуг')),
                ('date_from', models.DateField(blank=True, null=True, verbose_name='Дата начала предоставления услуги')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='Дата окончания предоставления услуги')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Комментарий')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to='backend.Address', verbose_name='Адрес')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='backend.Contract', verbose_name='Договор')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Цена услуги')),
            ],
            options={
                'verbose_name': 'Тип сервисной услуги',
                'verbose_name_plural': 'Типы сервисных услуг',
            },
        ),
        migrations.CreateModel(
            name='StreetType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
                ('short_name', models.CharField(max_length=4)),
            ],
            options={
                'verbose_name': 'Тип улицы',
                'verbose_name_plural': 'Типы улиц',
            },
        ),
        migrations.AddField(
            model_name='service',
            name='type_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='backend.ServiceType', verbose_name='Тип услуги'),
        ),
        migrations.AddField(
            model_name='contract',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='backend.Customer', verbose_name='Заказчик'),
        ),
        migrations.AddField(
            model_name='contract',
            name='executor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executors', to='backend.Customer', verbose_name='Исполнитель'),
        ),
        migrations.AddField(
            model_name='address',
            name='street_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.StreetType', verbose_name='Тип улицы'),
        ),
    ]
