# Generated by Django 2.1.1 on 2018-09-04 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Цена услуги'),
        ),
        migrations.AlterField(
            model_name='service',
            name='type_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='services', to='backend.ServiceType', verbose_name='Тип услуги'),
        ),
    ]
