# Generated by Django 2.1.1 on 2018-09-08 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('backend', '0002_auto_20180904_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='auth.Group', verbose_name='Группа'),
        ),
        migrations.AddField(
            model_name='contract',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='auth.Group', verbose_name='Группа'),
        ),
        migrations.AddField(
            model_name='customer',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='auth.Group', verbose_name='Группа'),
        ),
        migrations.AddField(
            model_name='service',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service', to='auth.Group', verbose_name='Группа'),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicetype', to='auth.Group', verbose_name='Группа'),
        ),
        migrations.AddField(
            model_name='streettype',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='streettype', to='auth.Group', verbose_name='Группа'),
        ),
    ]
