# Generated by Django 2.1.1 on 2018-09-11 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20180908_2138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Компания', 'verbose_name_plural': 'Компании'},
        ),
        migrations.AlterModelOptions(
            name='legacyentity',
            options={'verbose_name': 'Юридическое лицо', 'verbose_name_plural': 'Юридические лица'},
        ),
    ]
